version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      linter-and-formatter:
        patterns:
          - "@inialum/eslint-config"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
      storybook:
        patterns:
          - "storybook*"
          - "@storybook/*"
      test:
        patterns:
          - "@vitest/*"
          - "vitest*"
